# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Followrabbit < Formula
  desc "CLI for Rabbit cloud cost optimization"
  homepage "https://followrabbit.ai"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/followrabbit-ai/homebrew-tap/releases/download/v0.3.0/followrabbit_0.3.0_darwin_amd64.tar.gz"
      sha256 "f23ef91dc97ccc34c8d9cab4141efa28fe1c00dc26104ab90e9618e15f847f63"

      define_method(:install) do
        bin.install "followrabbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/followrabbit-ai/homebrew-tap/releases/download/v0.3.0/followrabbit_0.3.0_darwin_arm64.tar.gz"
      sha256 "9daea23a1f2087392a368cf695c363c85d658fe82b210e3d9035d1aaf418b937"

      define_method(:install) do
        bin.install "followrabbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/followrabbit-ai/homebrew-tap/releases/download/v0.3.0/followrabbit_0.3.0_linux_amd64.tar.gz"
      sha256 "efc73b6601ef932891a0a39b79caa7e1fc1ac198e16b69041ab845eb0fcebf73"
      define_method(:install) do
        bin.install "followrabbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/followrabbit-ai/homebrew-tap/releases/download/v0.3.0/followrabbit_0.3.0_linux_arm64.tar.gz"
      sha256 "7a33539e86c6f615a4448f53e4d3d9a7fd25c05a0b8e27406d1687abce9ae668"
      define_method(:install) do
        bin.install "followrabbit"
      end
    end
  end

  test do
    system "#{bin}/followrabbit", "version"
  end
end
