# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Followrabbit < Formula
  desc "CLI for Rabbit cloud cost optimization"
  homepage "https://followrabbit.ai"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/followrabbit-ai/homebrew-tap/releases/download/v0.1.1/followrabbit_0.1.1_darwin_amd64.tar.gz"
      sha256 "84bb06620731def8a35cc1a8dcdd1ec4557a673c5aca458c8157aa6b07b370af"

      define_method(:install) do
        bin.install "followrabbit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/followrabbit-ai/homebrew-tap/releases/download/v0.1.1/followrabbit_0.1.1_darwin_arm64.tar.gz"
      sha256 "68f4529b34d610b319fee497b6ef4fa5fcdc1f0fb757877878b7944a38b76a96"

      define_method(:install) do
        bin.install "followrabbit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/followrabbit-ai/homebrew-tap/releases/download/v0.1.1/followrabbit_0.1.1_linux_amd64.tar.gz"
      sha256 "7acabf195c80b3918d7a868c826dedc448dcd700240031770432976f3a3feedf"
      define_method(:install) do
        bin.install "followrabbit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/followrabbit-ai/homebrew-tap/releases/download/v0.1.1/followrabbit_0.1.1_linux_arm64.tar.gz"
      sha256 "7212fef657a9890d391ab2e53a89f1890f2173513de1260ee1cad6d16452c8c1"
      define_method(:install) do
        bin.install "followrabbit"
      end
    end
  end

  test do
    system "#{bin}/followrabbit", "version"
  end
end
